### ISSUE TITLE
Publishing on pypi

### ISSUE THREAD

**Issue by NickRoss** [dsi-clinic/cocoa#43]
Does this action work? 

What else needs to be done to get it so that we can pip install it via a github action?

**Comment by NickRoss** [comment]
The current flow (in the publish github action):
* When a user changes a tag the github action activates and publishes.

What we want it to do:
* When someone pushes to main
* update the _minor_ version 0.1.2 -> 0.1.3 -> 0.1.4 -> 0.1.5
* push the code to pypi with the minor version updated.

**Comment by chenhuifei01** [comment]
Three main issues for this week
1. increase the version by 0.2.0 → 0.3.0, not 0.2.1 →0.2.2
2. didn't automatically increase the version but manually change the version in set up files (.bumpversion.cfg, [setup.py](http://setup.py/), __init__.py)
3. hardcode the git identity in the publish.workflow.yml

**Comment by NickRoss** [comment]
The 3 issues above have new issues.
