### ISSUE TITLE
Run code against repos

### ISSUE THREAD

**Issue by NickRoss** [dsi-clinic/cocoa#47]
1. Tim/Nick add you to the appropriate repos
2. Run cocoa against the repo with a start date of the 3/18/24
3. maybe a google doc to share.

Important:
- Do the results look correct?
- Are we getting any errors when running?

**Comment by chenhuifei01** [comment]
https://docs.google.com/document/d/13eYaR4YvfczkiJZDuZdh8gB6AKctJEUVgWltrNRx5yg/edit?usp=sharing
[11:11](https://uchicagodsi.slack.com/archives/C06RK28Q9P1/p1715011903226379)
Here is the result for the five repos check. lmk if there is any problem

**Comment by NickRoss** [comment]
Complete!
