### ISSUE TITLE
Remove root directory from report

### ISSUE THREAD

**Issue by NickRoss** [dsi-clinic/cocoa#55]
1. Can we remove the root directory from reporting? 
	"Analyzing /Users/wangchenhui/Desktop/DSI-clinic-argonne-fermi/code/similarity_comb_ss.py"
	vs. 
	"Analyzing DSI-clinic-argonne-fermi/code/similarity_comb_ss.py"

**Comment by timhannifan** [comment]
This is resolved for the github action output and anytime a user runs with a relative path. This cannot be resolved for the case where a user runs cocoa locally using an absolute path.

**Comment by NickRoss** [comment]
Looks fixed!
